CREATE SEQUENCE Image_ID_Sequence
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCACHE;

CREATE TABLE Image (
Image_ID NUMBER(4, 0) DEFAULT Image_ID_Sequence.NEXTVAL CONSTRAINT PK_Image_ID PRIMARY KEY 
,Post_ID NUMBER(5, 0) CONSTRAINT FK_Image_Post_ID REFERENCES Post(Post_ID)
,File_Path VARCHAR2(512) CONSTRAINT UQ_Image_File_Path NOT NULL UNIQUE
,File_Name VARCHAR2(100) CONSTRAINT NN_Image_File_Name NOT NULL
);