CREATE SEQUENCE Thread_ID_Sequence
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCACHE;

CREATE TABLE THREAD (
Thread_ID NUMBER(4, 0) DEFAULT Thread_ID_Sequence.NEXTVAL CONSTRAINT PK_Thread_ID PRIMARY KEY 
,Thread_Name VARCHAR2(60) CONSTRAINT UQ_Thread_Name NOT NULL UNIQUE
,Creator_name VARCHAR2(100) DEFAULT '名無しさん'
,Create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
